---
title: "Media Franchise Revenues"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())

media_franchises <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")
```

```{r}
media_franchises %>%
  count(franchise, sort = TRUE)

franchises <- media_franchises %>%
  group_by(franchise, original_media, year_created, creators, owners) %>%
  summarize(categories = n(),
            total_revenue = sum(revenue),
            most_profitable = revenue_category[which.max(revenue)]) %>%
  ungroup()

franchises

media_franchises
```

### Franchise-level

What are the biggest franchises?

```{r}
library(glue)

top_franchises <- franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>%
  top_n(20, total_revenue)

media_franchises %>%
  mutate(franchise = glue("{ franchise } ({ year_created })")) %>%
  semi_join(top_franchises, by = "franchise") %>%
  mutate(franchise = fct_reorder(franchise, revenue, sum),
         revenue_category = fct_reorder(revenue_category, revenue, sum)) %>%
  ggplot(aes(franchise, revenue)) +
  geom_col(aes(fill = revenue_category)) +
  geom_text(aes(y = total_revenue,
                label = paste0(scales::dollar(total_revenue, accuracy = 1), "B")),
            data = top_franchises,
            hjust = 0) +
  scale_y_continuous(labels = scales::dollar) +
  expand_limits(y = 100) +
  coord_flip() +
  theme(panel.grid.major.y = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "What are the most profitable franchises of all time?",
       fill = "Category",
       x = "",
       y = "Revenue (Billions)")
```

```{r}
media_franchises %>%
  group_by(owners) %>%
  filter(n_distinct(franchise) > 2) %>%
  ungroup() %>%
  mutate(franchise = fct_reorder(franchise, revenue, sum),
         owners = fct_reorder(owners, -revenue, sum),
         revenue_category = fct_reorder(revenue_category, revenue, sum)) %>%
  ggplot(aes(franchise, revenue, fill = revenue_category)) +
  geom_col() +
  facet_wrap(~ owners, scales = "free_y") +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip() +
  labs(title = "What companies own at least 3 franchises?",
       fill = "Category",
       x = "",
       y = "Revenue (Billions)")
```

```{r}
franchises %>%
  ggplot(aes(year_created, total_revenue)) +
  geom_point(aes(size = total_revenue, color = original_media)) +
  geom_text(aes(label = franchise), check_overlap = TRUE, vjust = 1, hjust = 1) +
  expand_limits(x = 1910) +
  labs(title = "When were the 'great' franchises created?")
```

```{r}
media_franchises %>%
  group_by(original_media) %>%
  summarize(revenue = sum(revenue)) 

original_media_revenue_categories <- media_franchises %>%
  group_by(original_media) %>%
  filter(sum(revenue) >= 45) %>%
  group_by(original_media, revenue_category) %>%
  summarize(revenue = sum(revenue)) %>%
  ungroup() %>%
  mutate(revenue_category = fct_reorder(revenue_category, revenue, sum),
         original_media = fct_reorder(original_media, -revenue, sum))

original_media_revenue_categories %>%
  ggplot(aes(revenue_category, revenue)) +
  geom_col() +
  scale_y_continuous(labels = scales::dollar) +
  coord_flip() +
  facet_wrap(~ original_media) +
  labs(x = "Revenue category",
       y = "Revenue (Billions)",
       title = "What kinds of media lead to what types of revenue?")
```

```{r}
original_media_revenue_categories %>%
  mutate(revenue_category = fct_rev(revenue_category),
         original_media = fct_rev(original_media)) %>%
  ggplot(aes(revenue_category, original_media, fill = revenue)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", high = "red", labels = scales::dollar) +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(fill = "Revenue (billions)")
```


